In [16]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("edges.csv").sort_values('artist_a')

In [5]:
len(data['artist_a'].unique())

69108

In [6]:
data

release_id  year  artist_a  artist_b
119474          399  1998         1       674
973732      2387641  1999         1     12458
973729      2387641  1999         1     24023
973725      2387641  1999         1      1716
973720      2387641  1999         1     17870
...             ...   ...       ...       ...
1294405     6878646  1989   7753982   7753983
1585089    15007242  1996   7756428   7756429
1556605    12636144  1993   7758826   7758827
1656788    15027416  1999   7765143   7765144
1656789    15027451  1999   7765143   7765144

[1656791 rows x 4 columns]

In [48]:
1 in data['artist_b']

True

In [ ]:
"""
we need an artist to artist similarity matrix
for each artist, similarity score for each other artist

calculating similiarity: just number of collabs? then we can normalize? if we want?
"""

In [7]:
artist_slice = data[data['artist_a'] == 1]

In [8]:
artist_slice

release_id  year  artist_a  artist_b
119474         399  1998         1       674
973732     2387641  1999         1     12458
973729     2387641  1999         1     24023
973725     2387641  1999         1      1716
973720     2387641  1999         1     17870
973714     2387641  1999         1     49470
183018       62584  1997         1        89
215682      100650  1998         1       674
215676      100650  1998         1        83
215669      100650  1998         1      8602
171575       49823  1999         1    107031
801532     1795441  1998         1      1373
973707     2387641  1999         1        77
171497       49823  1999         1      1656
171511       49823  1999         1      2889
171574       49823  1999         1     20080
171573       49823  1999         1     40039
973699     2387641  1999         1      9169
171524       49823  1999         1      4594
171572       49823  1999         1     40038
171571       49823  1999         1      1068
171570       49823  1999         1     60320
10600      1167790  1998         1       674
171569       49823  1999         1     25820
171568       49823  1999         1      3361
171567       49823  1999         1     23215
171557       49823  1999         1      1509
171547       49823  1999         1      1552
171536       49823  1999         1    231513
801518     1795441  1998         1        35
973734     2387641  1999         1       328
973735     2387641  1999         1    101269
801503     1795441  1998         1    793362
139739       20209  1997         1       674
801568     1795441  1998         1       674
801580     1795441  1998         1     11069
215692      100650  1998         1     28902
801557     1795441  1998         1       817
801545     1795441  1998         1        31
801581     1795441  1998         1       816
119479         399  1998         1       675
801582     1795441  1998         1      3592
215688      100650  1998         1       263
215689      100650  1998         1        59
119480         399  1998         1       676
215690      100650  1998         1     25419
801583     1795441  1998         1     20662
801584     1795441  1998         1       174
215691      100650  1998         1     61020
801579     1795441  1998         1       179
801586     1795441  1998         1       957
801587     1795441  1998         1      6365
801588     1795441  1998         1      1661
119478         399  1998         1        50
801585     1795441  1998         1     22139

In [30]:
all_artist_ids = np.unique(np.concatenate((data['artist_a'].unique(), data['artist_b'].unique()), axis=None))

In [38]:
# collab_matrix = pd.DataFrame(data=None, index=all_artist_ids, columns=all_artist_ids)
# this takes forever

KeyboardInterrupt: 

In [70]:
collab_matrix = np.zeros((len(all_artist_ids), len(all_artist_ids)))

In [44]:
artist_one_collabs = collab_matrix[0]

In [49]:
artist_one = all_artist_ids[0]
artist_one

1

In [64]:
subslice = data[data['artist_a'] == artist_one]
subslice
# for entry in subslice.iterrows() :
#     collaborator_index = np.where(all_artist_ids == entry['artist_b'])
#     artist_one_collabs[collaborator_index] += 1

In [67]:
collaborator_index = np.where(all_artist_ids == one_row['artist_b'])
artist_one_collabs[collaborator_index] += 1

In [68]:
artist_one_collabs

array([0., 0., 0., ..., 0., 0., 0.])

In [71]:
test_idcs = [0,2]

In [92]:
id_1 = all_artist_ids[test_idcs[0]]
id_2 = all_artist_ids[test_idcs[1]]
sst = data[((data['artist_a'] == id_1) & (data['artist_b'] == 674)) | ((data['artist_a'] == id_2) & (data['artist_b'] == id_1))]

In [93]:
sst

release_id  year  artist_a  artist_b
119474         399  1998         1       674
215682      100650  1998         1       674
10600      1167790  1998         1       674
139739       20209  1997         1       674
801568     1795441  1998         1       674

In [101]:
for i in range(len(collab_matrix)): 
    for j in range(i, len(collab_matrix)):
        artist_1 = all_artist_ids[i]
        artist_2 = all_artist_ids[j]
        collab_matrix[i,j] = len(data[
            ((data['artist_a'] == id_1) & (data['artist_b'] == id_2)) 
            | ((data['artist_a'] == id_2) & (data['artist_b'] == id_1))
        ])

KeyboardInterrupt: 

In [106]:
# let's try this another way

! pip install igraph

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 14.0 MB/s eta 0:00:00m eta 0:00:010:00:01


In [107]:
import igraph

In [109]:
edgelist = data[['artist_a', 'artist_b']]

In [143]:
edgelist

artist_a  artist_b
119474          1       674
973732          1     12458
973729          1     24023
973725          1      1716
973720          1     17870
...           ...       ...
1294405   7753982   7753983
1585089   7756428   7756429
1556605   7758826   7758827
1656788   7765143   7765144
1656789   7765143   7765144

[1656791 rows x 2 columns]

In [144]:
len(
    edgelist[(edgelist['artist_a']  == 1) & (edgelist['artist_b'] == 674)]
)

5

In [145]:
sub = edgelist[edgelist['artist_a'] == 1]

In [147]:
sub['artist_b'].unique()

array([   674,  12458,  24023,   1716,  17870,  49470,     89,     83,
         8602, 107031,   1373,     77,   1656,   2889,  20080,  40039,
         9169,   4594,  40038,   1068,  60320,  25820,   3361,  23215,
         1509,   1552, 231513,     35,    328, 101269, 793362,  11069,
        28902,    817,     31,    816,    675,   3592,    263,     59,
          676,  25419,  20662,    174,  61020,    179,    957,   6365,
         1661,     50,  22139])

In [148]:
all_artist_ids

array([      1,       3,       4, ..., 7766420, 7769622, 7770446])

In [153]:
edgelist.iloc[0]

artist_a      1
artist_b    674
Name: 119474, dtype: int64

In [154]:
el_sample = edgelist.sample(10)

In [157]:
def increment_weight(row) :
    i = np.where(all_artist_ids == row['artist_a'])
    j = np.where(all_artist_ids == row['artist_b'])
    collab_matrix[i,j] += 1

In [159]:
! pip install swifter

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 830.9/830.9 kB 14.2 MB/s eta 0:00:00m eta 0:00:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.8 MB/s eta 0:00:0031m30.5 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 3.1 MB/s eta 0:00:00
  Using cached cloudpickle-2.2.0-py3-none-any.whl (25 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.5/139.5 kB 5.7 MB/s eta 0:00:00
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
  Using cached partd-1.3.0-py3-none-any.whl (18 kB)
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.6/197.6 kB 5.8 MB/s eta 0:00:00
  Using cached locket-1.0.0-py2.py3-none-any.whl (4.4 kB)


  Created wheel for swifter: filename=swifter-1.3.4-py3-none-any.whl size=16300 sha256=83fbfe030e5875191153cdd3cdd67b9cd01754622d2ab1f4b288a225744dc13c
  Stored in directory: /Users/rglass/Library/Caches/pip/wheels/40/ac/82/e6e08c451973c2764ee709b175a5b899866119bccf5206a65d
Successfully built swifter


In [160]:
import swifter

In [1]:
edgelist.swifter.apply(increment_weight, axis=1)

NameError: name 'edgelist' is not defined

In [ ]:
g = igraph.Graph.DataFrame(edgelist, )

In [124]:
g.es['weight'] = 1.

In [125]:
g.is_weighted()

True

In [126]:
g[1, 674]

1.0

In [127]:
g = igraph.Graph()

In [136]:
g.es['weight'] = 1.

In [137]:
g.is_weighted()

True